#!/bin/bash

cd "$HOME/Apps/crawlers"
if bundle exec ruby "asa.sgnavi.com/anemone.rb"
then
  bundle exec ruby "asa.sgnavi.com/nokogiri.rb"
fi 

if bundle exec ruby "shufukita.jp/anemone.rb"
then
  bundle exec ruby "shufukita.jp/nokogiri.rb"
fi 

bundle exec ruby "generate_html.rb"
