#!/bin/bash
#
# (1) copy to: ~/bin/ssh-host-color 
# (2) set:     alias ssh=~/bin/ssh-host-color
#
# Inspired from http://talkfast.org/2011/01/10/ssh-host-color
# Fork from https://gist.github.com/773849
#

if [[ "$@" =~ marketing.local ]]; then
  printf "\033]50;SetProfile=marketing.local\007"
elif [[ "$@" =~ liner-tool.local ]]; then
  printf "\033]50;SetProfile=liner-tool.local\007"
elif [[ "$@" =~ s1.liner.jp ]]; then
  printf "\033]50;SetProfile=s1.liner.jp\007"
elif [[ "$@" =~ app-server ]]; then
  printf "\033]50;SetProfile=app-server\007"
else
  printf "\033]50;SetProfile=Default\007"
fi

ssh $@
printf "\033]50;SetProfile=Default\007"
