Rails:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Style/CommentedKeyword:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
