Rails:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - c
    - i
    - n
    - id
    - q

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
